name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Run test with coverage
        run: npm run test

      - name: Generate coverage badge
        run: npm run test:badge

      - name: Commit badge using Bot
        uses: IAreKyleW00t/verified-bot-commit@v1
        with:
          message: 'feat: Some changes'
          files: |
            .github/badges/coverage.svg