name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Run test with coverage
        run: npm run test

      - name: Generate coverage badge
        run: npm run coverage:badge

      - name: Commit badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .github/badges/coverage.svg
          git commit -m "update coverage badge" || echo "No changes"
          git push